name: JSON Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jsonlint
        run: sudo apt install python3-demjson

      - name: Lint repos/*.json
        run: |
          jsonlint repos/*.json
